<?php
namespace OpenCloud\Orchestration\Enum;

class StackStatus
{
    const CREATE_IN_PROGRESS = 'CREATE_IN_PROGRESS';
    const CREATE_COMPLETE = 'CREATE_COMPLETE';
    const CREATE_FAILED = 'CREATE_FAILED';

    const DELETE_IN_PROGRESS = 'DELETE_IN_PROGRESS';
    const DELETE_COMPLETE = 'DELETE_COMPLETE';
    const DELETE_FAILED = 'DELETE_FAILED';

    const UPDATE_IN_PROGRESS = 'UPDATE_IN_PROGRESS';
    const UPDATE_COMPLETE = 'UPDATE_COMPLETE';
    const UPDATE_FAILED = 'UPDATE_FAILED';

    const ROLLBACK_IN_PROGRESS = 'ROLLBACK_IN_PROGRESS';
    const ROLLBACK_COMPLETE = 'ROLLBACK_COMPLETE';
    const ROLLBACK_FAILED = 'ROLLBACK_FAILED';

    const SUSPEND_IN_PROGRESS = 'SUSPEND_IN_PROGRESS';
    const SUSPEND_COMPLETE = 'SUSPEND_COMPLETE';
    const SUSPEND_FAILED = 'SUSPEND_FAILED';

    const RESUME_IN_PROGRESS = 'RESUME_IN_PROGRESS';
    const RESUME_COMPLETE = 'RESUME_COMPLETE';
    const RESUME_FAILED = 'RESUME_FAILED';

    const ADOPT_IN_PROGRESS = 'ADOPT_IN_PROGRESS';
    const ADOPT_COMPLETE = 'ADOPT_COMPLETE';
    const ADOPT_FAILED = 'ADOPT_FAILED';
}